language: ruby
before_install:
  - gem update --system
  - gem update bundler
  - gem cleanup bundler
matrix:
  include:
    - rvm: 2.4.0
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.3.0
      gemfile: gemfiles/rails_4.2.gemfile
    - rvm: 2.3.0
      gemfile: gemfiles/rails_4.2.gemfile
