language: ruby
before_install:
  - gem update --system
  - gem update bundler
  - gem cleanup bundler
cache: bundler
matrix:
  fast_finish: true
  include:
    - rvm: 2.4.0
      gemfile: gemfiles/rails5.0.gemfile
    - rvm: 2.3.0
      gemfile: gemfiles/rails4.2.gemfile
    - rvm: 2.3.0
      gemfile: gemfiles/rails5.0.gemfile
