language: ruby
before_install:
  - gem update --system
  - gem update bundler
  - gem cleanup bundler
rvm:
  - 2.3.0
  - 2.4.0
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
matrix:
  exclude:
  - rvm: 2.4.0
    gemfile: gemfiles/rails4.2.gemfile
